### ISSUE TITLE
使用连接器读取maxcompute上的未分区表出现的问题

### ISSUE THREAD

**Issue by hongqiang008** [RealtimeCompute/ververica-connector-demo#1]
java.lang.RuntimeException: ODPS-0110031: Invalid object type - a-----_h is not a partitioned table.
表不是个分区表，conf内也没有设置分区字段，一运行就会报这个问题

Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: ODPS-0110031: Invalid object type - ads_rpt_dev.t118_sl_after_sale_vehicle_a_h is not a partitioned table.
	at com.alibaba.ververica.connectors.common.source.reader.ParallelReader.run(ParallelReader.java:211)
	at com.alibaba.ververica.connectors.common.source.AbstractParallelSourceBase.run(AbstractParallelSourceBase.java:217)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:269)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: ODPS-0110031: Invalid object type - ads_rpa_h is not a partitioned table.
	at com.alibaba.ververica.connectors.common.source.reader.ParallelReader.runImpl(ParallelReader.java:290)
	at com.alibaba.ververica.connectors.common.source.reader.ParallelReader.run(ParallelReader.java:206)
	... 4 more

**Comment by cshuo** [comment]
你好, 如果方便的话建议贴下 代码, 另外贴下完整异常栈.
